config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'
  root 'elements#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :elements, :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors
  validates_presence_of :title, :author, :publisher, :published_year
  validates :isbn, presence: true

  def get_image_url
    if isbn
      client = OpenBD::Client.new
      client.search(isbns: isbn).resources.first.cover_image
    end
  end
end

app/models/element.rb
# == Schema Information
#
# Table name: elements
#
#  id         :integer          not null, primary key
#  title      :string
#  citation   :text
#  source     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Element < ApplicationRecord
  validates_presence_of :title, :citation, :source
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Successfully created a new book!"
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Successfully updated"
      redirect_to @book
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  private
    def book_params
      params.require(:book).permit(
        :title, :author, :publisher, :published_year, :isbn
      )
    end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  def index
    @elements = Element.all
  end

  def new
    @element = Element.new
  end

  def create
    @element = Element.new(element_params)
    if @element.save
      flash[:success] = "Successfully created a new baby piece"
      redirect_to elements_url
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @element = Element.find(params[:id])
  end

  private
    def element_params
      params.require(:element).permit(
        :title, :citation, :source
      )
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f| %>
  <%= render "shared/errors", object: f.object %>

  <%= f.label :title, class: "control-label" %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :author, class: "control-label" %>
  <%= f.text_field :author, class: "form-control" %>

  <%= f.label :publisher, class: "control-label" %>
  <%= f.text_field :publisher, class: "form-control" %>

  <%= f.label :publised_year, class: "control-label" %>
  <%= f.number_field :published_year, class: "form-control" %>

  <%= f.label :isbn, class: "control-label" %>
  <%= f.text_field :isbn, class: "form-control" %>

  <%= f.submit "Save / Update", class: "btn btn-primary mt-2" %>
<% end %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>

<%= render "form" %>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<nav class="nav nav-buttons">
  <%= link_to "new", new_book_path, class: "btn btn-primary mb-2" %>
</nav>
<main>
  <table class="table table-hover">
    <thead>
      <th>title</th>
      <th>author</th>
      <th>published year</th>
      <th>isbn</th>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to book.title, book %></td>
          <td><%= book.author %></td>
          <td><%= book.published_year %></td>
          <td><%= book.isbn %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/books/new.html.erb
<h1>新しい本を登録</h1>

<%= render "form" %>

app/views/books/show.html.erb
<h1>Books#show</h1>

<h2> <%= @book.title %><small class="author text-muted"> <%= @book.author %> </small> </h2>

<div class="image">
  <%= image_tag @book.get_image_url, height: "250" if @book.isbn %>
</div>

<div class="nav nav-buttons mt-2">
  <%= link_to "edit", edit_book_path(@book), class: "btn btn-secondary" %>
  <%= link_to "back to index", books_path, class: "btn btn-secondary ml-2" %>
</div>

app/views/elements/edit.html.erb
<h1>Elements#edit</h1>
<p>Find me in app/views/elements/edit.html.erb</p>

app/views/elements/index.html.erb
<h1>ピースの素</h1>
<p>論文の素になるピースの素です。</p>

<nav class="nav nav-buttons mb-2">
  <%= link_to "New", new_element_path, class: "btn btn-primary" %>
  <%= link_to "Books", books_path, class: "btn btn-primary ml-2" %>
</nav>
<main>
  <table class="table table-hover">
    <thead>
      <th>title</th>
      <th>citation</th>
      <th>source</th>
    </thead>
    <tbody>
      <% @elements.each do |e| %>
        <tr>
          <td><%= link_to e.title, e %></td>
          <td><%= e.citation.truncate(20) %></td>
          <td><%= e.source %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

app/views/elements/new.html.erb
<h1>Element of a Piece</h1>
<p>ピースの素となる情報を作りましょう</p>

<%= form_with model: @element, local: true do |f| %>
  <%= render "shared/errors", object: f.object %>

  <%= f.label :title, class: "control-label" %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :citation, class: "control-label" %>
  <%= f.text_area :citation, class: "form-control" %>

  <%= f.label :source, class: "control-label" %>
  <%= f.text_field :source, class: "form-control mb-2" %>

  <%= f.submit "Save / Update", class: "btn btn-primary" %>
<% end %>

app/views/elements/show.html.erb
<h1 class="element-title mt-2 pl-3"> <%= @element.title %></h1>

<div class="citation mt-3">
  <%= @element.citation %>
</div>

<h6 class="element-source mt-2">
  出典：『<%= @element.source %>』
</h6>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <%= link_to image_tag("think.png", height: "40"), root_url %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PieceOfEssays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container col-md-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1 class="title">このサイトについて</h1>

<div class="callout">
  <p>This is home page of Ronbun Piece Maker. You can make some pieces of a thesis, a report or an essay using this application. Usage is below.</p>

  <p>これは論文のピースメーカーと名前をつけたものです。論文の部品を作るためのアプリです。</p>

  <p>論文には部品となる小さなまとまりがあります。大雑把に、引用とコメント、その引用がなぜ引かれているのかという説明から成り立っています。</p>

  <p>この構成は共通しているので、論文を書くための部品作りに、何か役立つものが作れないかと思ったのです。</p>

  <p>大きな論文を書くのは大変なものです。長い道のりの一歩を踏み進めていくために、このアプリを作りました。</p>

  <p>みなさんの論文作成のお役に立てれば幸せです😌</p>
</div>

app/views/static_pages/home.html.erb
<h1 class="title">Home</h1>
<p>welcome to piece maker!🙋‍♂️</p>

<p>piece maker is a generator and stock place for academic-porpose writings.</p>

<p>you can make <i>pieces</i> of what you are writing or to be writing.</p>

<p>let's begin to create your awesome academic papers.</p>